// <auto-generated />
namespace Apteka.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DosageForm300 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DosageForm300));
        
        string IMigrationMetadata.Id
        {
            get { return "201906111659459_DosageForm300"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
